# Generated by Django 3.2.16 on 2023-09-23 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230922_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество не может быть меньше 1'), django.core.validators.MaxValueValidator(32000, message='Количество не может быть больше 32000')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время не может быть меньше 1 мин.'), django.core.validators.MaxValueValidator(32000, message='Так долго готовить недопустимо!')], verbose_name='Время приготовления'),
        ),
    ]
